// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projekatWP_bar.Model;

namespace projekatWP_bar.Migrations
{
    [DbContext(typeof(TakmicenjeContext))]
    [Migration("20210324004637_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("projekatWP_bar.Model.Klub", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("Datum_prijave")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Datum_prijave");

                    b.Property<string>("Ime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ime");

                    b.Property<int?>("TakmicenjeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TakmicenjeID");

                    b.ToTable("Klub");
                });

            modelBuilder.Entity("projekatWP_bar.Model.Takmicar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("Ime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ime");

                    b.Property<string>("Kategorija")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Kategorija");

                    b.Property<int>("Kilaza")
                        .HasColumnType("int")
                        .HasColumnName("Kilaza");

                    b.Property<int?>("KlubID")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Prezime");

                    b.HasKey("ID");

                    b.HasIndex("KlubID");

                    b.ToTable("Takmicar");
                });

            modelBuilder.Entity("projekatWP_bar.Model.Takmicenje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("Ime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ime");

                    b.HasKey("ID");

                    b.ToTable("Takmicenje");
                });

            modelBuilder.Entity("projekatWP_bar.Model.Klub", b =>
                {
                    b.HasOne("projekatWP_bar.Model.Takmicenje", "Takmicenje")
                        .WithMany("Klubovi")
                        .HasForeignKey("TakmicenjeID");

                    b.Navigation("Takmicenje");
                });

            modelBuilder.Entity("projekatWP_bar.Model.Takmicar", b =>
                {
                    b.HasOne("projekatWP_bar.Model.Klub", "Klub")
                        .WithMany("Takmicari")
                        .HasForeignKey("KlubID");

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("projekatWP_bar.Model.Klub", b =>
                {
                    b.Navigation("Takmicari");
                });

            modelBuilder.Entity("projekatWP_bar.Model.Takmicenje", b =>
                {
                    b.Navigation("Klubovi");
                });
#pragma warning restore 612, 618
        }
    }
}
